version: "3.9"
services:
  app:
    build: .
    container_name: myapp
    restart: always
    ports:
      - "4000:4000" # usa el PORT de tu .env
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: proyecto       
      MYSQL_USER: myuser             
      MYSQL_PASSWORD: mypassword     
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
